default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:

development:
  <<: *default
  database: rails6-bootstrap-agency_development

test:
  <<: *default
  database: rails6-bootstrap-agency_test

production:
  <<: *default
  database: rails6-bootstrap-agency_production
  username: rails6-bootstrap-agency
  password: <%= ENV['RAILS6_BOOTSTRAP_AGENCY_DATABASE_PASSWORD'] %>
